### ISSUE TITLE
phase_R1b not set

### ISSUE THREAD

**Issue by thkirchner** [marsandav/ABCDmodelPCMR#1]
just fyi phase_R1b is not set in this
it should be 0, right?

nice work btw. thank you!

**Comment by marsandav** [comment]
Dear Thomas,

Thank you very much for letting me know! I have amended the script now. And yes, phase_R1b is 0.

Best wishes,
David
________________________________
From: Thomas Kirchner ***@***.***>
Sent: 16 May 2023 11:36
To: marsandav/ABCDmodelPCMR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [marsandav/ABCDmodelPCMR] phase_R1b not set (Issue #1)


⚠ Caution: External sender


just fyi phase_R1b is not set in this
it should be 0, right?

nice work btw. thank you!

**Comment by thkirchner** [comment]
perfect thanks for the quick confirmation
